.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bop-audit 1  "audit " 
.SH NAME
bop\-audit \- Scan system and show power optimization findings
.SH SYNOPSIS
\fBbop audit\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Scan system and show power optimization findings
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON instead of formatted tables
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
