.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bop-status 1  "status " 
.SH NAME
bop\-status \- Show current optimization state and detect drift
.SH SYNOPSIS
\fBbop status\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show current optimization state and detect drift
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON instead of formatted tables
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
