.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bop-wake 1  "wake " 
.SH NAME
bop\-wake \- Manage expansion card wakeup sources (Framework\-specific)
.SH SYNOPSIS
\fBbop wake\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage expansion card wakeup sources (Framework\-specific)
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON instead of formatted tables
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
bop\-wake\-list(1)
List all USB controllers, connected devices, and wake status
.TP
bop\-wake\-enable(1)
Enable wakeup for a controller
.TP
bop\-wake\-disable(1)
Disable wakeup for a controller
.TP
bop\-wake\-scan(1)
Re\-scan controllers and auto\-enable wake for those with connected devices
