.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bop-wake-disable 1  "disable " 
.SH NAME
bop\-wake\-disable \- Disable wakeup for a controller
.SH SYNOPSIS
\fBbop wake disable\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICONTROLLER\fR> 
.SH DESCRIPTION
Disable wakeup for a controller
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON instead of formatted tables
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICONTROLLER\fR>
Controller name (e.g., XHC1)
