.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bop-apply 1  "apply " 
.SH NAME
bop\-apply \- Apply recommended optimizations
.SH SYNOPSIS
\fBbop apply\fR [\fB\-\-dry\-run\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Apply recommended optimizations
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR
Show what would be changed without applying
.TP
\fB\-\-json\fR
Output as JSON instead of formatted tables
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
